### ISSUE TITLE
Emotion class naming

### ISSUE THREAD

**Issue by DarkoKukovec** [infinum/frontend-handbook#16]
It's a good idea to mark emotion variables somehow (e.g. suffixing with `Class`) so it's clear that it's not something else.

I think we should define:
* suffix we're using (seen `Style`, `Css` and `Class`, liking `Class` the most)
* should we have a separate suffix for functions that return classes (`mainClass(12, 23)` looks weird, maybe `ClassFn` or something like that?)

**Comment by isBatak** [comment]
- `Class` at first seem as the most suitable suffix, but on the other hand `Css` is shorter and we are actually using emotion's `css({...})` helper with the same name, so my vote goes to `Css`

**Comment by isBatak** [comment]
In emotion 10 `css` helper no more returns class name, instead it returns object with signature
```
{
  name: string,
  styles: string,
  map: string,
}
```
So it doesn't make sense to suffix variable with `Class`, `Css` suits better in this case.
