### ISSUE TITLE
React fragment

### ISSUE THREAD

**Issue by DarkoKukovec** [infinum/frontend-handbook#18]
How should we use the react fragment:
* `<>`
* `<Fragment>` / `<React.Fragment>`

**Comment by kristijanbambir** [comment]
I vote for `<Fragment>…</Fragment>` to be explicit and to avoid editor highlighting and linter support.

**Comment by kedius** [comment]
> I vote for `<Fragment>…</Fragment>` to be explicit and to avoid editor highlighting and linter support.

What about * as React import? Is it React.Fragment normal to use?

**Comment by DarkoKukovec** [comment]
Yes, I would say that either `Fragment` or `React.Fragment` would be fine.
