### ISSUE TITLE
Emotion 10

### ISSUE THREAD

**Issue by DarkoKukovec** [infinum/frontend-handbook#25]
Emotion 10 was released recently and although it doesn't seem to have any breaking changes (at least not relevant to our use cases), it has some deprecation warnings that are problematic:

[Migration guide](https://next.emotion.sh/docs/migrating-to-emotion-10)

# Changes

## `css` prop

```diff
- const { css } from 'emotion';
+ /** @jsx jsx */
+ const { css, jsx } from '@emotion/core';

const mainClass = css`
  display: block;
`;

const Home = () => (
  <div
-    className={mainClass}
+    css={mainClass}
  >
    Hello world
  </div>
);
```

The `@jsx` comment can be avoided if a separate babel plugin is used, but this is not an option for CRA projects.

## No more `cx`

```diff
- import { css, cx } from 'emotion';
+ /** @jsx jsx */
+ const { css, jsx } from '@emotion/core';

const mainClass = css`
  display: block;
`;

const importantClass = css`
  font-weight: bold;
`;

const Home = ({ important }) => (
  <div
-    className={cx(mainClass, { [importantClass]: important })}
+    css={[mainClass, important && importantClass]}
  >
    Hello world
  </div>
);
```

This isn't necessarily a bad change, but it depends on the new `css` prop.

## No more class interpolation for nesting

This doesn't seem to be possible to do without class interpolation:

```jsx
import { css } from 'emotion';

const childClass = css`
  display: none;
`;

const containerClass = css`
  &:hover .${childClass} {
    display: block;
  }
`;

const Home = () => (
  <div className={containerClass}>
    <h1>Hello world</h1>
    <div className={childClass}>Hi there!</div>
  </div>
);
```

The docs only mention the possibility of nesting based on fixed selectors like tag names, pseudo-selectors or hardcoded class names: https://next.emotion.sh/docs/nested

# Next steps

My concern is that the first change adds significant boilerplate to the project, and the third change is even more problematic, since I don't see an alternative for this use case.

Our options are:

### Keep using Emotion 10
Keep using Emotion 10 even when Emotion 11 is released and ignore warnings.
In the long term this means no bugfixes, no security updates, potential compatibility issues.

### Upgrade
Probably means more boilerplate and some limitations we didn't have until now.

### Use the pure Emotion without any React integration
This solution still doesn't avoid the interpolation issue, and we lose support for theming. We might also need an alternative for `cx` (`classnames`?) as it's not clear if `cx` is deprecated in general or only when used in React.

### Move on
Start using something else. This seems like a step back for me, but it might be the best option. Now that Create React App supports SCSS and CSS modules, this might be a way forward.

**Comment by DarkoKukovec** [comment]
Feedback about the class interpolation: https://github.com/emotion-js/emotion/issues/1186

**Comment by isBatak** [comment]
soon! https://github.com/JedWatson/react-select/pull/3321
