### ISSUE TITLE
Ternary operator formatting

### ISSUE THREAD

**Issue by fvoska** [infinum/frontend-handbook#29]
I think we should decide how we want to format ternary operators.

Problem arises when ternary operator is broken into multiple lines - where do we place `?` and `:`?

I see three valid options:

1️⃣ 
```js
const result = someLongCondition
  ? someLongResult
  : someOtherLongResult;
```

2️⃣ 
```js
const result = someLongCondition ?
  someLongResult :
  someOtherLongResult;
```
3️⃣
> Do not use ternary operator if it does not fit in one line's max-length.
> 3️⃣ . 1️⃣ Use `if` 
> 3️⃣ . 2️⃣ store condition, true value and false value in variables and use variables in ternary to make it fit in one line
----

I vote 1️⃣ 

My personal reasoning why I like option 1️⃣ more than 2️⃣ is because when I read line-by-line and come to lines 2 and 3 it is clear that this is ternary operator. In option 2️⃣ when I come to lines 2 and 3 I am like "why is this indented?".

But I might even like 3️⃣ . 2️⃣ , I am not sure.

Discuss :)

**Comment by kristijanbambir** [comment]
I would not force 3️⃣ since it adds more code, and sometimes even if the statement would fit into one, it's nicer to split it into more lines (common in JSX). I vote for 2️⃣.

**Comment by DarkoKukovec** [comment]
I have the same reasoning against 3️⃣ as @kristijanbambir, but my vote is for 1️⃣

**Comment by nives113** [comment]
I agree with reasoning against 3️⃣. Usually I use 2️⃣, but I'm fine with both 1️⃣ and 2️⃣ .

**Comment by domagojkorman** [comment]
I find 3.2 pretty reasonable as it adds clarity to long condition statements that might not be clear from the first look at the code. Of course it depends on the case and whether it makes sense.

Also 3.1 is something that makes sense but again, depends on the case. As @kristijanbambir said, I would not force it.

Regarding specific style, I vote for 2️⃣ . I think it is much clearer when these specific characters are visible at the beginning of the line as you can immediately see them and understand what is happening in the line.

**Comment by DarkoKukovec** [comment]
The conclusion from our last discussion is that we shouldn't be concerned with that and leave it to Prettier (and therefore 1️⃣)
