### ISSUE TITLE
Bad links

### ISSUE THREAD

**Issue by kristian240** [infinum/frontend-handbook#48]
Because of proofreading the handbook some subpages changed the titles, which broke the links to them, e.g. BEM -> Stylesheets.

List of broken links
 - Javascript
   - Styleguide -changed to-> Style guide (still not merged so please check this one when resolving the issue)
 - BEM
   - Stylesheets -changed to-> Style sheets 
   - Javascripts -changed to-> JavaScript

**Comment by andreicek** [comment]
Closing as stale
