### ISSUE TITLE
Angular folder structure clarifications

### ISSUE THREAD

**Issue by ibrcic** [infinum/frontend-handbook#56]
Hi, I've recently started using Infinum's Angular folder structure recommendations in my projects because I find them quite good and logical. I especially like the `/pages` and `/components` distinction which lets us easily discern between top level routing components and standalone components used in templates.

However, I am not sure how should I approach this in large projects with lazy loaded modules each of which has pages, components and other sub-modules of its own. To demonstrate the problem, imagine that you have a  web shop kind of app that has `customer` and `admin` modules. Both of those modules are lazily loaded and have their own set of pages and components as well as other lazily loaded submodules.

How would you approach this in regard to folder structure. Should there only be `app/pages` and `app/components` that contain pages and components from both `customer` and `admin` submodules or should both of those modules have their own `components/` and `pages/` directories. Basically, should every module containing routing has its own `pages/` and `components/` subdirectories?

I'm not sure if this kind of discussion is welcome here from someone not at Infinum, but since I find your handbook excellent, might as well ask what do you think about this.

**Comment by fvoska** [comment]
Hi @ibrcic, sorry for the late reply.

Our handbook is a set of general guidelines and best practices which we try to adhere to as much as possible. There are, of course, cases where something is not completely covered by the handbook or where exceptions should be made.

File organization section of the handbook is one of the sections which can vary the most from project to project. As you said, for large projects it is a good idea to have even more separation between modules which share very little and have many components of their own which are not used inside other top-level route modules.

Just like you, we also experience this in some projects. In such cases we usually create another components directory inside pages/some-module directory. Example structure for such a case:

- `components/`
  - `picture/`
  - `button/`
  - `sidebar/`
  - `card/`
- `pages/`
  - `customer-container/`
    - `customer-container.module.ts`
    - `customer-container.component.ts`
    - `components/`
      - `customer-card/`
    - `sub-pages/`
      - `customers-list/`
      - `customer-details/`
  - `admin-container/`
    - `admin-container.module.ts`
    - `admin-container.component.ts`
    - `components/`
      - `admin-card/`
    - `sub-pages/`
      - `admins-list/`
      - `admin-details/`

Components inside admin and customer containers might still use common picture, button, card, etc. components, but they also have their own components. If the app is really big, `sub-pages/` for customer and admin pages might again have their own nested `component/` and `sub-pages/` dirs.

It is really up to you to decide what works the best for your use case. Two most important things to keep in mind is to keep things maintainable and easy to find, even for new developer which might start working on the project.

I hope this helps you with deciding what kind of structure you want.

**Comment by ibrcic** [comment]
Hi, thanks for the reply!
I guess it all comes down to balance between how "deep" of a structure you want to have and simplicity of flatter structure. It seems more logical to have deeper structure where everything is nicely and logically separated, but that can result in complexity when project grows when some component is 5+ levels deep. I always find it interesting how flat [Angular Material](https://github.com/angular/components/tree/master/src/material/dialog) is, with each component having only one directory, no matter the number of files. 

Anyway, thanks for you great reply, I'll close the issue since I got the answer.
