### ISSUE TITLE
Broken links in the repository

### ISSUE THREAD

**Issue by filipjakov** [infinum/frontend-handbook#72]
## The problem

After finding some broken links in the handbook, I've decided to check the repo for broken links using [markdown-link-check](https://github.com/tcort/markdown-link-check).

## Reproducing the problem:

- I've ran `find */*.md -exec npx markdown-link-check {} \\;` in the root of the project
- found some broken links:

1. FILE: Angular/Angular guidelines and best practices.md

```
ERROR: 5 dead links found!
[✖] /img/angular.svg → Status: 400
[✖] /img/real_programmers.png → Status: 400
[✖] https://marketplace.visualstudio.com/items?itemName=shinnn.stylelint → Status: 404
[✖] https://github.com/ReactiveX/rxjs/blob/master/doc/pipeable-operators.md → Status: 404
[✖] https://github.com/ReactiveX/rxjs/blob/master/doc/operator-creation.md#operator-as-a-pure-function → Status: 404
```

2. FILE: Angular/Getting started with Angular.md

```
ERROR: 1 dead links found!
[✖] /img/angular.svg → Status: 400
```

3. FILE: Frontend/Useful links.md

```
ERROR: 2 dead links found!
[✖] http://susydocs.oddbird.net/en/latest/ → Status: 404
[✖] https://www.webpackbin.com/ → Status: 0
```

4. FILE: JavaScript/Predeployment checklist.md

```
ERROR: 2 dead links found!
[✖] http://www.imdb.com/title/tt0117500/&quot; → Status: 404
[✖] https://search.google.com/search-console/mobile-friendly → Status: 404
```

5. FILE: JavaScript/Styleguide.md

```
ERROR: 2 dead links found!
[✖] JS%20Styleguide → Status: 400
[✖] http://jsrocks.org/2015/01/temporal-dead-zone-tdz-demystified/ → Status: 404
```

6. FILE: SASS Styleguide/Code quality.md

```
ERROR: 1 dead links found!
[✖] https://github.com/infinum/dotfiles/blob/master/code-linters/scss-lint.yml → Status: 404
```

**NOTE**: some of these are false positives (images served locally) - by defining a config file, markdown-link-check can either ignore these patterns or check for them on the server serving them (check [config](https://github.com/tcort/markdown-link-check#command-line-tool) options)

## Possible courses of action

If we are to integrate this in the toolchain, there are a couple of solutions that come to find (after introducing the lib to the project and providing a feasible config):

1. Someone periodically runs the above-provided command and fixes the broken links/raises issues with the people responsible for that particular part of the handbook
2. We integrate it in our git flow: husky + precommit hook for new changes (prevention)
3. A bot/service that runs the command periodically and opens up issues (something like github's dependabot)

What do you think?

**Comment by kristijanbambir** [comment]
Thanks for looking into this. Since there are false positives, I don't think integrating it into git would work. I would go with the first option, to run it once in a while. Anything more would I think require involvement from the backend team.
It would be good if you could clean out these links. Some of them maybe moved to a different location.

**Comment by fvoska** [comment]
It would be nice if we could run it for external links only and ignore internal ones.

**Comment by filipjakov** [comment]
@fvoska yep, can be done. Will investigate and inform you :D

**Comment by filipjakov** [comment]
@fvoska @kristijanbambir 

I tried the following command to find the broken links:

`find . -type f -name '*.md' ! -path './node_modules/*' | sed 's/ /\\ /g' | xargs -L1 npx markdown-link-check --quiet --progress --config config.json`

It consists of 3 parts (pipe segments):

1. Finds all the markdown files in the current directory and excludes the node_modules (we currently don't have them in the repo)
2. Since we name some files with whitespaces, I escape the whitespaces
3. I apply the markdown link check to each found markdown file:
- `--quiet` - shows only errors
- `--progress` - shows the current progress on linting a certain file
- `--config` - points to the config file

I have a prototype of the config file, it currently looks like the following (there are more options in the official docs):

```
json
{
  "ignorePatterns": [
    {
      "pattern": "^/img/*"
    }
  ]
}
```

this ignores the links that point to local images. And we solve some FPs :D I'll investigate for further patterns to ignore or enhance, but for now, local referencing can be ignored I think (another parts of the handbook, other resources on the same domain). The tool provides to define the `replacementPatterns` in the config, but it's not flexible (we can replace only hardcoded strings).

## Next step

1. install the tool as a local dependency, introduce package(-lock).json
2. define the command in the script
3. update the readme

What do you think? Does it make sense?

**Comment by andreicek** [comment]
@filipjakov can you re-run the tool and see if there is anything new here?

we can do this as a github action if we can get it to not return false positives.

**Comment by andreicek** [comment]
Please if still relevant move to discussions.
